# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|

  # Box
  #config.vm.box = "StefanScherer/windows_2019"
  config.vm.box = "gusztavvargadr/windows-10"
  config.vm.box_check_update = false
# Additional parameters to communicate with Windows
  
  config.vm.boot_timeout = 600
  config.vm.communicator = "winrm"
  config.winrm.port = 55985

  # Customization
  config.vm.provider "virtualbox" do |v|
    v.name = "my_win10"
    v.gui = true
    v.cpus = 2
    v.memory = 4096
    v.customize ["modifyvm", :id, "--draganddrop", "hosttoguest"] # Enables drag-and-drop between host and guest
  end
  #config.vm.network :forwarded_port, guest: 80, host: 8080, id: "http"
  config.vm.network "private_network", ip: "192.168.33.10"
  #config.vm.network "public_network", bridge: "Realtek USB GbE Family Controller #2"
  #config.vm.network "public_network", bridge: "Intel(R) Wi-Fi 6 AX200 160MHz"
  # Provisioning
  #config.vm.provision "shell", inline: <<-SHELL
     #Invoke-WebRequest -Uri https://community.chocolatey.org/install.ps1 -OutFile InstallChocolatey.ps1
     #Set-ExecutionPolicy Bypass -Scope Process -Force; InstallChocolatey.ps1
     #
  #SHELL
  #config.vm.provision "shell", path: "scripts/InstallChocolatey.ps1"
  #config.vm.provision "shell", inline: "whoami"
  #Start-Process "C:\vagrant\Autologon.exe" -ArgumentList "Vagrant","vagrant","vagrant","-accepteula"
  #config.vm.provision "shell", inline: "C:\\vagrant\\Autologon.exe Vagrant vagrant vagrant -accepteula"
  config.vm.provision "shell", path: "scripts/setup.ps1"
end
